name : SimpleFill
version : 1.0.3
api : 3.6.0

main : rark\simple_fill\Main
author : Rark

#<UpDdate Log>
#
#[1.0.0]
#リリース
#
#
#[1.0.1]
#無駄なコードの削除
#
#
#[1.0.2]
#pharアーカイブだと動作しない問題を修正
#
#
#[1.0.3]
#警告フォームが表示された場合の処理で、
#Undoのデータに正しく保存されない問題を修正
#
#PMMPサーバー上でPCプラットフォームでプレイする際に発生する
#右クリック判定が連続で発生する問題の対処のため
#アイテムをもってスニークで使用する方法を追加
#
#Undoのデータ保存量をユーザ側で設定できるように変更